# 
baseURL = "http://blog.funimg.top/"

# 网站标题
title = "学无止境的博客"

languageCode = "zh-CN"

# theme = "maupassant"
theme = "jane"


# 其它配置 start
enableRobotsTXT = true
enableEmoji = true

## 自动检测是否包含 中文\日文\韩文
hasCJKLanguage = true
## 首页每页显示的文章数
paginate = 3
## 限制 Rss 文章输出数量
rssLimit = 20

# 其它配置 end


# 作者
[author]
  name = "学无止境"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# 配置目录
[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "Home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "关于我"
  weight = 50
  identifier = "about"
  url = "/about"
  # url = "https://github.com/zhaoshuxue"


[params]
  since = "2019" # 站点建立时间
  homeFullContent = false # if false, show post summaries on home page. Othewise show full content.

# 全局开关，也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）

# 是否显示字数统计与阅读时间
  moreMeta = true

  [params.counter.busuanzi]  # a Chinese visitor counter  # 不蒜子计数器
    enable = true

  [params.social]
    a-email = "mailto:zhaoshuxue@163.com"
    b-github = "https://github.com/zhaoshuxue"
    c-weibo = "https://weibo.com/2971537913"
    g-google = "https://www.google.com/"